apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: app-pv
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: app-pv
        volumeMounts:
          - name: volume-mnt
            mountPath: "/mnt"
      volumes:
      - name: volume-mnt
        persistentVolumeClaim:
          claimName: nfs-pvc
