apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-foo
spec:
  tls:
  - hosts:
    - sslfoo.csp.local
    secretName: test-tls
  rules:
  - host: sslfoo.csp.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 80