apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  - host: test.csp.local
    http:
      paths:
      - backend:
          serviceName: nginx-svc
          servicePort: 80