apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-foo
spec:
  rules:
  - host: foo.csp.local
    http:
      paths:
      - backend:
          serviceName: nginx-foo
          servicePort: 80