apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-bar
spec:
  - host: bar.csp.local
    http:
      paths:
      - backend:
          serviceName: nginx-bar
          servicePort: 80